language: node_js
node_js:
  - 4
  - 6
  - 8
cache:
  directories:
    - node_modules
before_install:
  # Upgrade npm
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@latest; fi
script:
  # Run lint
  - npm run lint
  # Run tests and Danger.js
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "4" ]]; then
      NODE_ENV=test node --harmony-proxies $(npm bin)/jest --runInBand
    else
      if [[ "$TRAVIS_NODE_VERSION" == "8" ]]; then
        npm run danger
        npm run test:coverage -- --runInBand
      else
        npm run test:jest -- --runInBand
      fi
    fi
  # Build all examples
  - npm run build
  - npm run build:customised
  - npm run build:sections
  # Check that examples really works: no JS errors on load
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "8" ]]; then
      npm run test:browser:pre
      npm run test:browser
      npm run test:browser:customised
      npm run test:browser:sections
    fi
after_success:
  # Make release with semantic-release if needed
  - npm install -g semantic-release
  - npm install --no-save semantic-release-tamia
  - semantic-release pre && npm publish && semantic-release post
  - |
    if [[ "$TRAVIS_NODE_VERSION" == "8" ]]; then
      # Upload coverage report to Codecov
      bash <(curl -s https://codecov.io/bash)
      # Update site
      if [[ "$TRAVIS_BRANCH" == "master" ]]; then
        curl -X POST -d '{}' https://api.netlify.com/build_hooks/591308eba700c425fc1e8a54
      fi
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
