language: node_js
node_js:
  - 6
  - 8
  - 9
env:
  - WEBPACK_VERSION= # Current, from package.json
  - WEBPACK_VERSION=3
cache:
  directories:
    - node_modules
before_install:
  # Upgrade npm
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@latest; fi
before_script:
  # Install Webpack version
  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
script:
  # Run tests without coverage since it's 2x faster
  - npm run test:jest -- --runInBand
  # Build all examples
  - npm run build
  - npm run build:customised
  - npm run build:sections
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - lint
  - test
  - integration
  - coverage
  - release
  - name: documentation
    if: branch = master
jobs:
  include:
    - stage: lint
      node_js: lts/*
      script:
        - npm run lint
        - npx danger ci

    - stage: integration
      node_js: lts/*
      script:
        # Check that examples really works: no JS errors on load
        - npm run test:browser:pre
        - npm run test:browser
        - npm run test:browser:customised
        - npm run test:browser:sections
        # Run integration tests with Cypress
        - npm run test:cypress:pre
        - npm run test:cypress:startServer &
        - npm run test:cypress:startServer:post
        - npm run test:cypress:run

    - stage: coverage
      node_js: lts/*
      script:
        # Run tests with coverage
        - npm run test:coverage -- --runInBand
        # Upload coverage report to Codecov
        - bash <(curl -s https://codecov.io/bash)

    - stage: release
      node_js: lts/*
      script:
        - npm install --no-save semantic-release-tamia
        - npx semantic-release \
        - --analyze-commits semantic-release-tamia/analyzeCommits \
        - --verify-release semantic-release-tamia/verifyRelease \
        - --generate-notes semantic-release-tamia/generateNotes

    - stage: documentation
      node_js: lts/*
      script:
        - curl -X POST -d '{}' https://api.netlify.com/build_hooks/591308eba700c425fc1e8a54
